name: Test JS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web

    steps:
    - uses: actions/checkout@v2
    - name: Setup node 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'yarn'
        working-directory: web

    - name: Install dependencies
      run: yarn install

    - name: Run tests
      run: yarn test
